# Generated by Django 4.0 on 2023-07-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORDER', 'Pedido'), ('COMPLETED', 'Venta completada'), ('CANCELED', 'Cancelada')], max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha venta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha modificacion venta')),
            ],
        ),
    ]
